### ISSUE TITLE
Unable to build on MacOS 12 arm64

### ISSUE THREAD

**Issue by Traace** [AloXado320/sm64ex-alo#31]
**Describe the bug**
Unable to build sm64ex-alo on macOS, error while compiling.

**To Reproduce**
1. Install packages needed to compile via brew
2. Extract Game Assets
3. Compile with 'gmake' (GNU Make) and GCC 12.2.0

**Expected behavior**
It should build successfully and provide a binary.

**Error**
`
Building tools...
In file included from /opt/homebrew/Cellar/gcc/12.2.0/lib/gcc/current/gcc/aarch64-apple-darwin21/12/include-fixed/stdio.h:413,
                 from aiff_extract_codebook.c:8:
aiff_extract_codebook.c:30:12: error: expected declaration specifiers or '...' before numeric constant
   30 | extern int vsnprintf(char * __restrict, size_t, const char * __restrict, va_list);
      |            ^~~~~~~~~
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/secure/_strings.h:33,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/strings.h:97,
                 from /Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/usr/include/string.h:184,
                 from aiff_extract_codebook.c:7:
aiff_extract_codebook.c:30:12: error: expected declaration specifiers or '...' before '__builtin_object_size'
   30 | extern int vsnprintf(char * __restrict, size_t, const char * __restrict, va_list);
      |            ^~~~~~~~~
gmake: *** [Makefile:74: aiff_extract_codebook] Error 1
Makefile:396: *** Failed to build tools.  Stop.
`

**Desktop: **
 - OS: MacOS Monterey
 - Device: Mac Mini 2020
 - Arch: arm64
 - Gmake Version: 4.3
 - GCC Version: 12.2.0

**Comment by AloXado320** [comment]
PR #22 should fix macOS compilation for real this time.
